language: node_js
node_js:
  - "8"

install:
  - yarn
  - yarn lerna run prepare

script:
  - yarn commitlint-travis
  - yarn test

after_success:
  - test $TRAVIS_BRANCH = "master" && test TRAVIS_EVENT_TYPE = "push" &&
    yarn storybook:publish
  