export type TCalendarTheme = {
	container?: string,
	header?: string,
	header__text?: string,
	changeMonth__container?: string,
	changeMonth__icon?: string,
	month?: string,
	monthHeader?: string,
	monthHeader__day?: string,
	week?: string,
	day?: string,
	day_disabled?: string,
	day_current?: string,
	day_selected?: string,
};